/* DO NOT EDIT THIS FILE - it is machine generated */
#include "idl2jni_jni.h"
/* Header for class i2jrt_ORB */

#ifndef _Included_i2jrt_ORB
#define _Included_i2jrt_ORB
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     i2jrt_ORB
 * Method:    _jni_fini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_i2jrt_ORB__1jni_1fini
  (JNIEnv *, jobject);

/*
 * Class:     i2jrt_ORB
 * Method:    init
 * Signature: (Lorg/omg/CORBA/StringSeqHolder;Ljava/lang/String;)Li2jrt/ORB;
 */
JNIEXPORT jobject JNICALL Java_i2jrt_ORB_init
  (JNIEnv *, jclass, jobject, jstring);

/*
 * Class:     i2jrt_ORB
 * Method:    object_to_string
 * Signature: (Lorg/omg/CORBA/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_i2jrt_ORB_object_1to_1string
  (JNIEnv *, jobject, jobject);

/*
 * Class:     i2jrt_ORB
 * Method:    string_to_object
 * Signature: (Ljava/lang/String;)Lorg/omg/CORBA/Object;
 */
JNIEXPORT jobject JNICALL Java_i2jrt_ORB_string_1to_1object
  (JNIEnv *, jobject, jstring);

/*
 * Class:     i2jrt_ORB
 * Method:    shutdown
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_i2jrt_ORB_shutdown
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     i2jrt_ORB
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_i2jrt_ORB_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
