# -*- makefile -*-
#----------------------------------------------------------------------------
#       GNU ACE Workspace
#
# $Id: GNUACEWorkspaceCreator.pm 2490 2015-03-20 20:50:04Z mitza $
#
# This file was generated by MPC.  Any changes made directly to
# this file will be lost the next time it is generated.
#
# MPC Command:
# /mnt/openDDS/OpenDDS-3.8/ACE_wrappers/bin/mwc.pl -type gnuace /mnt/openDDS/OpenDDS-3.8/DDS_TAOv2_all.mwc
#
#----------------------------------------------------------------------------

MAKEFILE = GNUmakefile

ifeq ($(findstring k,$(MAKEFLAGS)),k)
  KEEP_GOING = -
endif

include $(ACE_ROOT)/include/makeinclude/macros.GNU

all: idl2jni_codegen idl2jni_runtime tao_java dcps_java idl2jni_test_simple messenger_idl_test builtintopics_test complex_idl_test hello_java_client java_both_test publisher_idl_test subscriber_idl_test multirepo_test transport_config zerocopy_java_test

depend: idl2jni_codegen-depend idl2jni_runtime-depend tao_java-depend dcps_java-depend idl2jni_test_simple-depend messenger_idl_test-depend builtintopics_test-depend complex_idl_test-depend hello_java_client-depend java_both_test-depend publisher_idl_test-depend subscriber_idl_test-depend multirepo_test-depend transport_config-depend zerocopy_java_test-depend

REMAINING_TARGETS := $(filter-out all depend,$(TARGETS_NESTED:.nested=)) $(CUSTOM_TARGETS)

$(REMAINING_TARGETS):
	$(KEEP_GOING)@cd idl2jni/codegen && $(MAKE) -f GNUmakefile.idl2jni_codegen $(@)
	$(KEEP_GOING)@cd idl2jni/runtime && $(MAKE) -f GNUmakefile.idl2jni_runtime $(@)
	$(KEEP_GOING)@cd tao && $(MAKE) -f GNUmakefile.tao_java $(@)
	$(KEEP_GOING)@cd dds && $(MAKE) -f GNUmakefile.dcps_java $(@)
	$(KEEP_GOING)@cd idl2jni/tests/simple && $(MAKE) -f GNUmakefile.idl2jni_test_simple $(@)
	$(KEEP_GOING)@cd tests/messenger/messenger_idl && $(MAKE) -f GNUmakefile.messenger_idl_test $(@)
	$(KEEP_GOING)@cd tests/builtintopics && $(MAKE) -f GNUmakefile.builtintopics_test $(@)
	$(KEEP_GOING)@cd tests/complex_idl && $(MAKE) -f GNUmakefile.complex_idl_test $(@)
	$(KEEP_GOING)@cd tests/hello && $(MAKE) -f GNUmakefile.hello_java_client $(@)
	$(KEEP_GOING)@cd tests/messenger/both && $(MAKE) -f GNUmakefile.java_both_test $(@)
	$(KEEP_GOING)@cd tests/messenger/publisher && $(MAKE) -f GNUmakefile.publisher_idl_test $(@)
	$(KEEP_GOING)@cd tests/messenger/subscriber && $(MAKE) -f GNUmakefile.subscriber_idl_test $(@)
	$(KEEP_GOING)@cd tests/multirepo && $(MAKE) -f GNUmakefile.multirepo_test $(@)
	$(KEEP_GOING)@cd tests/transport_config && $(MAKE) -f GNUmakefile.transport_config $(@)
	$(KEEP_GOING)@cd tests/zerocopy && $(MAKE) -f GNUmakefile.zerocopy_java_test $(@)

.PHONY: idl2jni_codegen
idl2jni_codegen:
	$(KEEP_GOING)@cd idl2jni/codegen && $(MAKE) -f GNUmakefile.idl2jni_codegen all

.PHONY: idl2jni_codegen-depend
idl2jni_codegen-depend:
	$(KEEP_GOING)@cd idl2jni/codegen && $(MAKE) -f GNUmakefile.idl2jni_codegen depend

.PHONY: idl2jni_runtime
idl2jni_runtime:
	$(KEEP_GOING)@cd idl2jni/runtime && $(MAKE) -f GNUmakefile.idl2jni_runtime all

.PHONY: idl2jni_runtime-depend
idl2jni_runtime-depend:
	$(KEEP_GOING)@cd idl2jni/runtime && $(MAKE) -f GNUmakefile.idl2jni_runtime depend

.PHONY: tao_java
tao_java: idl2jni_codegen idl2jni_runtime
	$(KEEP_GOING)@cd tao && $(MAKE) -f GNUmakefile.tao_java all

.PHONY: tao_java-depend
tao_java-depend:
	$(KEEP_GOING)@cd tao && $(MAKE) -f GNUmakefile.tao_java depend

.PHONY: dcps_java
dcps_java: idl2jni_codegen idl2jni_runtime tao_java
	$(KEEP_GOING)@cd dds && $(MAKE) -f GNUmakefile.dcps_java all

.PHONY: dcps_java-depend
dcps_java-depend:
	$(KEEP_GOING)@cd dds && $(MAKE) -f GNUmakefile.dcps_java depend

.PHONY: idl2jni_test_simple
idl2jni_test_simple: idl2jni_codegen idl2jni_runtime
	$(KEEP_GOING)@cd idl2jni/tests/simple && $(MAKE) -f GNUmakefile.idl2jni_test_simple all

.PHONY: idl2jni_test_simple-depend
idl2jni_test_simple-depend:
	$(KEEP_GOING)@cd idl2jni/tests/simple && $(MAKE) -f GNUmakefile.idl2jni_test_simple depend

.PHONY: messenger_idl_test
messenger_idl_test: idl2jni_codegen idl2jni_runtime dcps_java
	$(KEEP_GOING)@cd tests/messenger/messenger_idl && $(MAKE) -f GNUmakefile.messenger_idl_test all

.PHONY: messenger_idl_test-depend
messenger_idl_test-depend:
	$(KEEP_GOING)@cd tests/messenger/messenger_idl && $(MAKE) -f GNUmakefile.messenger_idl_test depend

.PHONY: builtintopics_test
builtintopics_test: idl2jni_codegen idl2jni_runtime dcps_java messenger_idl_test
	$(KEEP_GOING)@cd tests/builtintopics && $(MAKE) -f GNUmakefile.builtintopics_test all

.PHONY: builtintopics_test-depend
builtintopics_test-depend:
	$(KEEP_GOING)@cd tests/builtintopics && $(MAKE) -f GNUmakefile.builtintopics_test depend

.PHONY: complex_idl_test
complex_idl_test: idl2jni_codegen idl2jni_runtime dcps_java
	$(KEEP_GOING)@cd tests/complex_idl && $(MAKE) -f GNUmakefile.complex_idl_test all

.PHONY: complex_idl_test-depend
complex_idl_test-depend:
	$(KEEP_GOING)@cd tests/complex_idl && $(MAKE) -f GNUmakefile.complex_idl_test depend

.PHONY: hello_java_client
hello_java_client: idl2jni_codegen idl2jni_runtime
	$(KEEP_GOING)@cd tests/hello && $(MAKE) -f GNUmakefile.hello_java_client all

.PHONY: hello_java_client-depend
hello_java_client-depend:
	$(KEEP_GOING)@cd tests/hello && $(MAKE) -f GNUmakefile.hello_java_client depend

.PHONY: java_both_test
java_both_test: idl2jni_codegen idl2jni_runtime dcps_java messenger_idl_test
	$(KEEP_GOING)@cd tests/messenger/both && $(MAKE) -f GNUmakefile.java_both_test all

.PHONY: java_both_test-depend
java_both_test-depend:
	$(KEEP_GOING)@cd tests/messenger/both && $(MAKE) -f GNUmakefile.java_both_test depend

.PHONY: publisher_idl_test
publisher_idl_test: idl2jni_codegen idl2jni_runtime dcps_java messenger_idl_test
	$(KEEP_GOING)@cd tests/messenger/publisher && $(MAKE) -f GNUmakefile.publisher_idl_test all

.PHONY: publisher_idl_test-depend
publisher_idl_test-depend:
	$(KEEP_GOING)@cd tests/messenger/publisher && $(MAKE) -f GNUmakefile.publisher_idl_test depend

.PHONY: subscriber_idl_test
subscriber_idl_test: idl2jni_codegen idl2jni_runtime dcps_java messenger_idl_test
	$(KEEP_GOING)@cd tests/messenger/subscriber && $(MAKE) -f GNUmakefile.subscriber_idl_test all

.PHONY: subscriber_idl_test-depend
subscriber_idl_test-depend:
	$(KEEP_GOING)@cd tests/messenger/subscriber && $(MAKE) -f GNUmakefile.subscriber_idl_test depend

.PHONY: multirepo_test
multirepo_test: idl2jni_codegen idl2jni_runtime dcps_java
	$(KEEP_GOING)@cd tests/multirepo && $(MAKE) -f GNUmakefile.multirepo_test all

.PHONY: multirepo_test-depend
multirepo_test-depend:
	$(KEEP_GOING)@cd tests/multirepo && $(MAKE) -f GNUmakefile.multirepo_test depend

.PHONY: transport_config
transport_config: idl2jni_codegen idl2jni_runtime dcps_java
	$(KEEP_GOING)@cd tests/transport_config && $(MAKE) -f GNUmakefile.transport_config all

.PHONY: transport_config-depend
transport_config-depend:
	$(KEEP_GOING)@cd tests/transport_config && $(MAKE) -f GNUmakefile.transport_config depend

.PHONY: zerocopy_java_test
zerocopy_java_test: idl2jni_codegen idl2jni_runtime dcps_java messenger_idl_test
	$(KEEP_GOING)@cd tests/zerocopy && $(MAKE) -f GNUmakefile.zerocopy_java_test all

.PHONY: zerocopy_java_test-depend
zerocopy_java_test-depend:
	$(KEEP_GOING)@cd tests/zerocopy && $(MAKE) -f GNUmakefile.zerocopy_java_test depend

project_name_list:
	@echo dcps_java
	@echo idl2jni_codegen
	@echo idl2jni_runtime
	@echo idl2jni_test_simple
	@echo tao_java
	@echo builtintopics_test
	@echo complex_idl_test
	@echo hello_java_client
	@echo java_both_test
	@echo messenger_idl_test
	@echo publisher_idl_test
	@echo subscriber_idl_test
	@echo multirepo_test
	@echo transport_config
	@echo zerocopy_java_test
