#include "simpleJS.h"
#include "idl2jni_runtime.h"

/* Generated by ../../../../bin/idl2jni running on input file simple.idl */


/* Begin MODULE: simple */



/* Begin TYPEDEF: TestTypedef */


/* End TYPEDEF: TestTypedef */


/* Begin TYPEDEF: StringTypedef */


/* End TYPEDEF: StringTypedef */


/* Begin TYPEDEF: TestSeqTypedef */


/* End TYPEDEF: TestSeqTypedef */


/* Begin TYPEDEF: SeqOfTypedefedLong */


/* End TYPEDEF: SeqOfTypedefedLong */


/* Begin TYPEDEF: StringSeq */


/* End TYPEDEF: StringSeq */


/* Begin CONST: ArrayBounds */


/* End CONST: ArrayBounds */


/* Begin TYPEDEF: TestArrayTypedef */


/* End TYPEDEF: TestArrayTypedef */


/* Begin TYPEDEF: TestArrayTypedef2 */


/* End TYPEDEF: TestArrayTypedef2 */


/* Begin TYPEDEF: TestStringArray */


/* End TYPEDEF: TestStringArray */


/* Begin TYPEDEF: StringSeqSeq */


/* End TYPEDEF: StringSeqSeq */


/* Begin TYPEDEF: StringSeqSeqSeq */


/* End TYPEDEF: StringSeqSeqSeq */


/* Begin TYPEDEF: LongSeqSeq */


/* End TYPEDEF: LongSeqSeq */


/* Begin TYPEDEF: LongSeqSeqSeq */


/* End TYPEDEF: LongSeqSeqSeq */


/* Begin STRUCT: TestStruct */


/* End STRUCT: TestStruct */


/* Begin TYPEDEF: TestStructSequence */


/* End TYPEDEF: TestStructSequence */


/* Begin TYPEDEF: TestStructArray */


/* End TYPEDEF: TestStructArray */


/* Begin STRUCT: TestNestedStruct */


/* End STRUCT: TestNestedStruct */


/* Begin CONST: TestConstLong */


/* End CONST: TestConstLong */


/* Begin CONST: TIMESTAMP_INVALID_NSEC */


/* End CONST: TIMESTAMP_INVALID_NSEC */


/* Begin CONST: TestConstFloat */


/* End CONST: TestConstFloat */


/* Begin CONST: TestConstDouble */


/* End CONST: TestConstDouble */


/* Begin CONST: TestConstBool */


/* End CONST: TestConstBool */


/* Begin CONST: TestConstString */


/* End CONST: TestConstString */


/* Begin CONST: TestConstTypedef */


/* End CONST: TestConstTypedef */


/* Begin CONST: TestConstChar */


/* End CONST: TestConstChar */


/* Begin CONST: TestConstWchar */


/* End CONST: TestConstWchar */


/* Begin ENUM: TestEnum */


/* End ENUM: TestEnum */


/* Begin UNION: TestUnion1 */


/* End UNION: TestUnion1 */


/* Begin UNION: TestUnion2 */


/* End UNION: TestUnion2 */


/* Begin UNION: TestUnion4 */


/* End UNION: TestUnion4 */


/* Begin TYPEDEF: EnumSeq */


/* End TYPEDEF: EnumSeq */


/* Begin TYPEDEF: EnumArray */


/* End TYPEDEF: EnumArray */


/* Begin STRUCT: TestStructWithEnum */


/* End STRUCT: TestStructWithEnum */


/* Begin INTERFACE: TestInterf */


/* End INTERFACE: TestInterf */


/* Begin TYPEDEF: TestUnion2Seq */


/* End TYPEDEF: TestUnion2Seq */


/* Begin UNION: TestUnion3 */


/* End UNION: TestUnion3 */


/* Begin INTERFACE: TestInterf2 */


/* End INTERFACE: TestInterf2 */


/* Begin INTERFACE: TestInterf3 */


/* End INTERFACE: TestInterf3 */


/* Begin INTERFACE: TestLI */


/* End INTERFACE: TestLI */


/* Begin INTERFACE: Local2 */


/* End INTERFACE: Local2 */


/* Begin TYPEDEF: Local2Seq */


/* End TYPEDEF: Local2Seq */


/* Begin STRUCT: StructWithObjref */


/* End STRUCT: StructWithObjref */


/* Begin INTERFACE: Local3 */


/* End INTERFACE: Local3 */

/* End MODULE: simple */
