/* DO NOT EDIT THIS FILE - it is machine generated */
#include "idl2jni_jni.h"
/* Header for class DDS_PUBLISHER_QOS_DEFAULT */

#ifndef _Included_DDS_PUBLISHER_QOS_DEFAULT
#define _Included_DDS_PUBLISHER_QOS_DEFAULT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DDS_PUBLISHER_QOS_DEFAULT
 * Method:    get
 * Signature: ()LDDS/PublisherQos;
 */
JNIEXPORT jobject JNICALL Java_DDS_PUBLISHER_1QOS_1DEFAULT_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
