/* DO NOT EDIT THIS FILE - it is machine generated */
#include "idl2jni_jni.h"
/* Header for class DDS_SUBSCRIBER_QOS_DEFAULT */

#ifndef _Included_DDS_SUBSCRIBER_QOS_DEFAULT
#define _Included_DDS_SUBSCRIBER_QOS_DEFAULT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     DDS_SUBSCRIBER_QOS_DEFAULT
 * Method:    get
 * Signature: ()LDDS/SubscriberQos;
 */
JNIEXPORT jobject JNICALL Java_DDS_SUBSCRIBER_1QOS_1DEFAULT_get
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
