/* -*- C++ -*- */
#ifndef IDL2JNI_GENERATED_DDSDCPSCONDITIONSEQJC_H
#define IDL2JNI_GENERATED_DDSDCPSCONDITIONSEQJC_H
#include "DdsDcpsConditionSeqC.h"
#include "idl2jni_jni.h"
#include "idl2jni_runtime.h"
#include "dcps_java_export.h"
/* Generated by ../../bin/idl2jni running on input file ../../dds/DdsDcpsConditionSeq.idl */


/* Begin MODULE: DDS */



/* Begin INTERFACE-FWD: Condition */

dcps_java_Export
void copyToCxx (JNIEnv *jni, DDS::Condition_var &target, jobject source);
dcps_java_Export
void copyToJava (JNIEnv *jni, jobject &target, const DDS::Condition_var &source, bool createNewObject);

/* End INTERFACE-FWD: Condition */


/* Begin TYPEDEF: ConditionSeq */

dcps_java_Export
void copyToCxx (JNIEnv *jni, DDS::ConditionSeq &target, jobjectArray source);
dcps_java_Export
void copyToJava (JNIEnv *jni, jobjectArray &target, const DDS::ConditionSeq &source, bool createNewObject = false);

/* End TYPEDEF: ConditionSeq */

/* End MODULE: DDS */
#endif /* IDL2JNI_GENERATED_DDSDCPSCONDITIONSEQJC_H */
