/* DO NOT EDIT THIS FILE - it is machine generated */
#include "idl2jni_jni.h"
/* Header for class OpenDDS_DCPS_transport_TcpInst */

#ifndef _Included_OpenDDS_DCPS_transport_TcpInst
#define _Included_OpenDDS_DCPS_transport_TcpInst
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    getLocalAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OpenDDS_DCPS_transport_TcpInst_getLocalAddress
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    setLocalAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_TcpInst_setLocalAddress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    isEnableNagleAlgorithm
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_OpenDDS_DCPS_transport_TcpInst_isEnableNagleAlgorithm
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    setEnableNagleAlgorithm
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_TcpInst_setEnableNagleAlgorithm
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    getConnRetryInitialDelay
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_OpenDDS_DCPS_transport_TcpInst_getConnRetryInitialDelay
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    setConnRetryInitialDelay
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_TcpInst_setConnRetryInitialDelay
  (JNIEnv *, jobject, jint);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    getConnRetryBackoffMultiplier
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_OpenDDS_DCPS_transport_TcpInst_getConnRetryBackoffMultiplier
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    setConnRetryBackoffMultiplier
 * Signature: (D)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_TcpInst_setConnRetryBackoffMultiplier
  (JNIEnv *, jobject, jdouble);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    getConnRetryAttempts
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_OpenDDS_DCPS_transport_TcpInst_getConnRetryAttempts
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    setConnRetryAttempts
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_TcpInst_setConnRetryAttempts
  (JNIEnv *, jobject, jint);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    getMaxOutputPausePeriod
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_OpenDDS_DCPS_transport_TcpInst_getMaxOutputPausePeriod
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    setMaxOutputPausePeriod
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_TcpInst_setMaxOutputPausePeriod
  (JNIEnv *, jobject, jint);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    getPassiveReconnectDuration
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_OpenDDS_DCPS_transport_TcpInst_getPassiveReconnectDuration
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_TcpInst
 * Method:    setPassiveReconnectDuration
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_TcpInst_setPassiveReconnectDuration
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
