/* DO NOT EDIT THIS FILE - it is machine generated */
#include "idl2jni_jni.h"
/* Header for class OpenDDS_DCPS_transport_UdpInst */

#ifndef _Included_OpenDDS_DCPS_transport_UdpInst
#define _Included_OpenDDS_DCPS_transport_UdpInst
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenDDS_DCPS_transport_UdpInst
 * Method:    getLocalAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OpenDDS_DCPS_transport_UdpInst_getLocalAddress
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_UdpInst
 * Method:    setLocalAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_UdpInst_setLocalAddress
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
