/* DO NOT EDIT THIS FILE - it is machine generated */
#include "idl2jni_jni.h"
/* Header for class OpenDDS_DCPS_transport_RtpsUdpInst */

#ifndef _Included_OpenDDS_DCPS_transport_RtpsUdpInst
#define _Included_OpenDDS_DCPS_transport_RtpsUdpInst
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    getLocalAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_getLocalAddress
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    setLocalAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_setLocalAddress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    isUseMulticast
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_isUseMulticast
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    setUseMulticast
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_setUseMulticast
  (JNIEnv *, jobject, jboolean);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    getMulticastGroupAddress
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_getMulticastGroupAddress
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    setMulticastGroupAddress
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_setMulticastGroupAddress
  (JNIEnv *, jobject, jstring);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    getNakDepth
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_getNakDepth
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    setNakDepth
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_setNakDepth
  (JNIEnv *, jobject, jint);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    getNakResponseDelay
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_getNakResponseDelay
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    setNakResponseDelay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_setNakResponseDelay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    getHeartbeatPeriod
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_getHeartbeatPeriod
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    setHeartbeatPeriod
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_setHeartbeatPeriod
  (JNIEnv *, jobject, jlong);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    getHeartbeatResponseDelay
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_getHeartbeatResponseDelay
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    setHeartbeatResponseDelay
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_setHeartbeatResponseDelay
  (JNIEnv *, jobject, jlong);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    getHandshakeTimeout
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_getHandshakeTimeout
  (JNIEnv *, jobject);

/*
 * Class:     OpenDDS_DCPS_transport_RtpsUdpInst
 * Method:    setHandshakeTimeout
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_OpenDDS_DCPS_transport_RtpsUdpInst_setHandshakeTimeout
  (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
