#include "CharSeqJC.h"
#include "idl2jni_runtime.h"

/* Generated by ../../bin/idl2jni running on input file /mnt/openDDS/OpenDDS-3.8/ACE_wrappers/TAO/tao/CharSeq.pidl */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: CharSeq */

void copyToCxx (JNIEnv *jni, CORBA::CharSeq &target, jcharArray source)
{
  jcharArray arr = source;
  jsize len = jni->GetArrayLength (arr);
  target.length (len);
  jchar *buf = jni->GetCharArrayElements (arr, 0);
  for (CORBA::ULong i = 0; i < static_cast<CORBA::ULong> (len); ++i)
    {
      target[i] = static_cast<char> (buf[i]);
    }
  jni->ReleaseCharArrayElements (arr, buf, JNI_ABORT);
}

void copyToJava (JNIEnv *jni, jcharArray &target, const CORBA::CharSeq &source, bool createNewObject)
{
  jsize len = source.length ();
  jcharArray arr;
  if (!createNewObject && jni->GetArrayLength (target) != len) createNewObject = true;
  if (createNewObject)
    {
      arr = jni->NewCharArray (len);
    }
  else
    {
      arr = target;
    }
  jchar *buf = jni->GetCharArrayElements (arr, 0);
  for (CORBA::ULong i = 0; i < static_cast<CORBA::ULong> (len); ++i)
    {
      buf[i] = source[i];
    }
  jni->ReleaseCharArrayElements (arr, buf, 0);
  target = arr;
}


/* End TYPEDEF: CharSeq */

/* End MODULE: CORBA */
