#include "DoubleSeqJC.h"
#include "idl2jni_runtime.h"

/* Generated by ../../bin/idl2jni running on input file /mnt/openDDS/OpenDDS-3.8/ACE_wrappers/TAO/tao/DoubleSeq.pidl */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: DoubleSeq */

void copyToCxx (JNIEnv *jni, CORBA::DoubleSeq &target, jdoubleArray source)
{
  jdoubleArray arr = source;
  jsize len = jni->GetArrayLength (arr);
  target.length (len);
  jdouble *buf = jni->GetDoubleArrayElements (arr, 0);
  for (CORBA::ULong i = 0; i < static_cast<CORBA::ULong> (len); ++i)
    {
      target[i] = buf[i];
    }
  jni->ReleaseDoubleArrayElements (arr, buf, JNI_ABORT);
}

void copyToJava (JNIEnv *jni, jdoubleArray &target, const CORBA::DoubleSeq &source, bool createNewObject)
{
  jsize len = source.length ();
  jdoubleArray arr;
  if (!createNewObject && jni->GetArrayLength (target) != len) createNewObject = true;
  if (createNewObject)
    {
      arr = jni->NewDoubleArray (len);
    }
  else
    {
      arr = target;
    }
  jdouble *buf = jni->GetDoubleArrayElements (arr, 0);
  for (CORBA::ULong i = 0; i < static_cast<CORBA::ULong> (len); ++i)
    {
      buf[i] = source[i];
    }
  jni->ReleaseDoubleArrayElements (arr, buf, 0);
  target = arr;
}


/* End TYPEDEF: DoubleSeq */

/* End MODULE: CORBA */
