#include "FloatSeqJC.h"
#include "idl2jni_runtime.h"

/* Generated by ../../bin/idl2jni running on input file /mnt/openDDS/OpenDDS-3.8/ACE_wrappers/TAO/tao/FloatSeq.pidl */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: FloatSeq */

void copyToCxx (JNIEnv *jni, CORBA::FloatSeq &target, jfloatArray source)
{
  jfloatArray arr = source;
  jsize len = jni->GetArrayLength (arr);
  target.length (len);
  jfloat *buf = jni->GetFloatArrayElements (arr, 0);
  for (CORBA::ULong i = 0; i < static_cast<CORBA::ULong> (len); ++i)
    {
      target[i] = buf[i];
    }
  jni->ReleaseFloatArrayElements (arr, buf, JNI_ABORT);
}

void copyToJava (JNIEnv *jni, jfloatArray &target, const CORBA::FloatSeq &source, bool createNewObject)
{
  jsize len = source.length ();
  jfloatArray arr;
  if (!createNewObject && jni->GetArrayLength (target) != len) createNewObject = true;
  if (createNewObject)
    {
      arr = jni->NewFloatArray (len);
    }
  else
    {
      arr = target;
    }
  jfloat *buf = jni->GetFloatArrayElements (arr, 0);
  for (CORBA::ULong i = 0; i < static_cast<CORBA::ULong> (len); ++i)
    {
      buf[i] = source[i];
    }
  jni->ReleaseFloatArrayElements (arr, buf, 0);
  target = arr;
}


/* End TYPEDEF: FloatSeq */

/* End MODULE: CORBA */
