/* -*- C++ -*- */
#ifndef IDL2JNI_GENERATED_LONGLONGSEQJC_H
#define IDL2JNI_GENERATED_LONGLONGSEQJC_H
#include "tao/LongLongSeqC.h"
#include "idl2jni_jni.h"
#include "idl2jni_runtime.h"
#include "tao_java_export.h"
/* Generated by ../../bin/idl2jni running on input file /mnt/openDDS/OpenDDS-3.8/ACE_wrappers/TAO/tao/LongLongSeq.pidl */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: LongLongSeq */

tao_java_Export
void copyToCxx (JNIEnv *jni, CORBA::LongLongSeq &target, jlongArray source);
tao_java_Export
void copyToJava (JNIEnv *jni, jlongArray &target, const CORBA::LongLongSeq &source, bool createNewObject = false);

/* End TYPEDEF: LongLongSeq */

/* End MODULE: CORBA */
#endif /* IDL2JNI_GENERATED_LONGLONGSEQJC_H */
