/* -*- C++ -*- */
#ifndef IDL2JNI_GENERATED_ULONGSEQJC_H
#define IDL2JNI_GENERATED_ULONGSEQJC_H
#include "tao/ULongSeqC.h"
#include "idl2jni_jni.h"
#include "idl2jni_runtime.h"
#include "tao_java_export.h"
/* Generated by ../../bin/idl2jni running on input file /mnt/openDDS/OpenDDS-3.8/ACE_wrappers/TAO/tao/ULongSeq.pidl */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: ULongSeq */

tao_java_Export
void copyToCxx (JNIEnv *jni, CORBA::ULongSeq &target, jintArray source);
tao_java_Export
void copyToJava (JNIEnv *jni, jintArray &target, const CORBA::ULongSeq &source, bool createNewObject = false);

/* End TYPEDEF: ULongSeq */

/* End MODULE: CORBA */
#endif /* IDL2JNI_GENERATED_ULONGSEQJC_H */
