/* -*- C++ -*- */
#ifndef IDL2JNI_GENERATED_ULONGLONGSEQJC_H
#define IDL2JNI_GENERATED_ULONGLONGSEQJC_H
#include "tao/ULongLongSeqC.h"
#include "idl2jni_jni.h"
#include "idl2jni_runtime.h"
#include "tao_java_export.h"
/* Generated by ../../bin/idl2jni running on input file /mnt/openDDS/OpenDDS-3.8/ACE_wrappers/TAO/tao/ULongLongSeq.pidl */


/* Begin MODULE: CORBA */



/* Begin TYPEDEF: ULongLongSeq */

tao_java_Export
void copyToCxx (JNIEnv *jni, CORBA::ULongLongSeq &target, jlongArray source);
tao_java_Export
void copyToJava (JNIEnv *jni, jlongArray &target, const CORBA::ULongLongSeq &source, bool createNewObject = false);

/* End TYPEDEF: ULongLongSeq */

/* End MODULE: CORBA */
#endif /* IDL2JNI_GENERATED_ULONGLONGSEQJC_H */
